project_id = "pjdyaeprvtwoltynoqri"

[functions.rdstation-sync]
verify_jwt = false

[functions.parse-order-pdf]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.ical-feed]
verify_jwt = false

[functions.image-proxy]
verify_jwt = false

[functions.crm-analytics]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
